env:
  node: true
  browser: true
  es6: true
  jest: true
extends:
  - "eslint:recommended"
  - "prettier"
plugins:
  - "prettier"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  prettier/prettier:
    - error
    - trailingComma: "all"
      singleQuote: true
      printWidth: 100
      endOfLine: "auto"
      semi: false
